name: snippy-phylogenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snippy=4.6.0
  - gubbins
  - snp-sites=2.5.1
  - snp-dists=0.8.2
  - iqtree=2
  - shiptv=0.4.1
