name: snippy-phylogenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - snippy=4.6.0
  - clonalframeml=1.12
  - maskrc-svg=0.5
  - snp-sites=2.5.1
  - snp-dists=0.8.2
  - iqtree=2.1.2
